<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:ntf="http://www.furryaide/ws/Notification"
                  xmlns:status="http://www.furryaide/ws/StatusCodeService"
                  xmlns:op="http://www.furryaide/ws/NotificationOperations"
                  xmlns:tns="http://www.furryaide/ws/NotificationService"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  targetNamespace="http://www.furryaide/ws/NotificationService">

    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.furryaide/ws/Notification" schemaLocation="../schemas/notification.xsd"/>
            <xsd:import namespace="http://www.furryaide/ws/StatusCodeService" schemaLocation="../../../../../central-schemas/status-code.xsd"/>
            <xsd:import namespace="http://www.furryaide/ws/NotificationOperations" schemaLocation="../schemas/notification-operations.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="sendNotificationRequestMsg">
        <wsdl:part name="parameters" element="op:sendNotificationRequest"/>
    </wsdl:message>

    <wsdl:message name="sendNotificationResponseMsg">
        <wsdl:part name="parameters" element="op:sendNotificationResponse"/>
    </wsdl:message>

    <wsdl:portType name="NotificationServicePortType">
        <wsdl:operation name="sendNotification">
            <wsdl:input message="tns:sendNotificationRequestMsg"/>
            <wsdl:output message="tns:sendNotificationResponseMsg"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="NotificationServiceSOAPBinding" type="tns:NotificationServicePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="sendNotification">
            <soap:operation soapAction="sendNotification"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="NotificationService">
        <wsdl:port name="NotificationServicePort" binding="tns:NotificationServiceSOAPBinding">
            <soap:address location="http://localhost:5005/ws/notificationService"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
