<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
				  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
				  xmlns:auth="http://www.furryaide.com/authentication"
				  xmlns:tns="http://www.furryaide.com/authentication"
				  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
				  targetNamespace="http://www.furryaide.com/authentication">

	<wsdl:types>
		<xsd:schema>
<!--			<xsd:import namespace="http://www.wstutorial.com/ws/CustomerService" schemaLocation="../schemas/customer.xsd"/>-->
<!--			<xsd:import namespace="http://www.wstutorial.com/ws/StatusCodeService" schemaLocation="../schemas/status-code.xsd"/>-->
			<xsd:import namespace="http://www.furryaide.com/authentication" schemaLocation="../schemas/auth.xsd"/>
		</xsd:schema>


	</wsdl:types>



	<wsdl:message name="loginRequestMessage">
		<wsdl:part name="parameters" element="auth:loginRequest"/>
	</wsdl:message>
	<wsdl:message name="loginResponseMessage">
		<wsdl:part name="parameters" element="auth:loginResponse"/>
	</wsdl:message>

	<wsdl:portType name="AuthenticationServicePortType">
		<wsdl:operation name="login">
			<wsdl:input message="tns:loginRequestMessage"/>
			<wsdl:output message="tns:loginResponseMessage"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="authenticationServiceSOAPBinding" type="tns:AuthenticationServicePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="login">
			<soap:operation soapAction="login"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="AuthenticationService">
		<wsdl:port name="AuthenticationServicePort" binding="tns:authenticationServiceSOAPBinding">
			<soap:address location="http://localhost:3000/wsdlfirst/authenticationService" />
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>
